import { redis } from '@/lib/redis'
import { PagesShell } from '@/components/pages-shell'
import { PagesDetailView } from '@/components/pages-detail-view'
import { notFound } from 'next/navigation'
import { Metadata } from 'next'

interface PagesPageProps {
    params: Promise<{ id: string }>
}

const SITE_URL = 'https://omniknows.xyz'
const SITE_NAME = 'Omni Knows'
const COVER_URL = `${SITE_URL}/omniknows_canvas.png`

export async function generateMetadata({ params }: PagesPageProps): Promise<Metadata> {
    const { id } = await params
    const rawData = await redis.get(`publish:${id}`)

    if (!rawData) {
        return { title: { absolute: `Report Not Found | ${SITE_NAME}` } }
    }

    const data = typeof rawData === 'string' ? JSON.parse(rawData) : rawData
    const reportTitle = data.title || 'AI Research Report'
    const description = data.answer
        ? String(data.answer).replace(/<[^>]+>/g, '').slice(0, 160).trimEnd() + '…'
        : `An AI-generated research report created with ${SITE_NAME}.`
    const pageUrl = `${SITE_URL}/pages/${id}`

    return {
        title: { absolute: `${reportTitle} | ${SITE_NAME}` },
        description,
        openGraph: {
            type: 'article',
            title: reportTitle + ' | Omni Knows',
            description,
            url: pageUrl,
            siteName: SITE_NAME,
            locale: 'en_US',
        },
        twitter: {
            card: 'summary_large_image',
            title: reportTitle + ' | Omni Knows',
            description,
            creator: '@omniknows',
        },
        robots: { index: true, follow: true },
        alternates: { canonical: pageUrl },
    }
}

export default async function PagesPage({ params }: PagesPageProps) {
    const { id } = await params
    const rawData = await redis.get(`publish:${id}`)

    if (!rawData) notFound()

    const data = typeof rawData === 'string' ? JSON.parse(rawData) : rawData

    return (
        <PagesShell>
            <PagesDetailView
                id={id}
                title={data.title || 'AI Research Report'}
                markdown={data.answer || ''}
                author="Generated by Omni AI"
                publishedAt={typeof data?.created_at === 'string' ? data.created_at : undefined}
                tags={Array.isArray(data?.tags) ? data.tags : []}
                sources={Array.isArray(data?.sources) ? data.sources : []}
            />
        </PagesShell>
    )
}
