import { redis } from '@/lib/redis'
import { FinalAnswer } from '@/components/final-answer'
import { notFound } from 'next/navigation'
import { Metadata } from 'next'
import Link from 'next/link'

interface PagesPageProps {
    params: Promise<{ id: string }>
}

const SITE_URL = 'https://omniknows.xyz'
const SITE_NAME = 'Omni Knows'
const COVER_URL = `${SITE_URL}/omniknows_canvas.png`

export async function generateMetadata({ params }: PagesPageProps): Promise<Metadata> {
    const { id } = await params
    const rawData = await redis.get(`publish:${id}`)

    if (!rawData) {
        return { title: { absolute: `Report Not Found | ${SITE_NAME}` } }
    }

    const data = typeof rawData === 'string' ? JSON.parse(rawData) : rawData
    const reportTitle = data.title || 'AI Research Report'
    const description = data.answer
        ? String(data.answer).replace(/<[^>]+>/g, '').slice(0, 160).trimEnd() + '…'
        : `An AI-generated research report created with ${SITE_NAME}.`
    const pageUrl = `${SITE_URL}/pages/${id}`

    return {
        title: { absolute: `${reportTitle} | ${SITE_NAME}` },
        description,
        openGraph: {
            type: 'article',
            title: reportTitle + ' | Omni Knows',
            description,
            url: pageUrl,
            siteName: SITE_NAME,
            locale: 'en_US',
        },
        twitter: {
            card: 'summary_large_image',
            title: reportTitle + ' | Omni Knows',
            description,
            creator: '@omniknows',
        },
        robots: { index: true, follow: true },
        alternates: { canonical: pageUrl },
    }
}

export default async function PagesPage({ params }: PagesPageProps) {
    const { id } = await params
    const rawData = await redis.get(`publish:${id}`)

    if (!rawData) notFound()

    const data = typeof rawData === 'string' ? JSON.parse(rawData) : rawData

    return (
        <div className="min-h-screen bg-[var(--background)] flex flex-col py-8 px-4 sm:px-6">
            {/* Report card */}
            <div className="max-w-[1200px] w-full mx-auto flex-1">
                <FinalAnswer
                    answer={data.answer}
                    sources={data.sources}
                    assets={data.assets}
                    title={data.title}
                    isReadOnly={true}
                />
            </div>

            {/* Footer */}
            <footer className="max-w-[1200px] w-full mx-auto mt-8 pt-4 border-t border-border">
                <div className="flex flex-col items-center gap-1 text-[10px] text-muted-foreground/60">
                    <b>Answers generated by AI. Check important info.</b>
                    <p>
                        © {new Date().getFullYear()}{' '}
                        <Link
                            href="https://omniknows.xyz"
                            target="_blank"
                            rel="noopener noreferrer"
                            className="underline underline-offset-2 decoration-muted-foreground/30 hover:decoration-foreground hover:text-foreground transition-colors font-[family-name:var(--font-plex)]"
                        >
                            Omni Knows
                        </Link>
                        {'. All rights reserved.'}
                    </p>
                    <p>
                        Made with love by{' '}
                        <Link
                            href="https://haozhe.li"
                            target="_blank"
                            rel="noopener noreferrer"
                            className="underline underline-offset-2 decoration-muted-foreground/30 hover:decoration-foreground hover:text-foreground transition-colors"
                        >
                            Haozhe Li
                        </Link>
                    </p>
                </div>
            </footer>
        </div>
    )
}
